CREATE OR REPLACE PROCEDURE SYMPHONY."SP_DN_ODS_LOAD_TO_SDB_REG_X86"
IS
/*---------------------------------------------------------------------------------------------
 SYSTEM       : GLOBAL-SCM                                                   
 PROGRAM ID   : SP_DN_ODS_LOAD_TO_SDB_REG
 PROGRAM DESC : DNE - OUTBOUND             
 CREATE DATE  : 2019.01.16                                                 
 CREATE BY    : NETTING TF                                                            
 DESCRIPTION  : NETTING 엔진OUTBOUND 테이블 구성 (X86서버)
---------------------------------------------------------------------------------------------*/

    V_PLANID          MST_PLAN.PLANID %TYPE ;
    V_PLANWEEK        MST_PLAN.PLANWEEK%TYPE ;
    V_EFFSTARTDATE    MST_PLAN.EFFSTARTDATE %TYPE ;
    V_EFFENDDATE      MST_PLAN.EFFENDDATE %TYPE ;
        
BEGIN
    
    SP_FN_GET_PLANID('NCP',V_PLANID,V_PLANWEEK,V_EFFSTARTDATE,V_EFFENDDATE) ;     

    DBMS_OUTPUT.PUT_LINE('PLANID: '||V_PLANID);        

    DBMS_OUTPUT.PUT_LINE('EXP_SOPROMISESRCNCP START['||TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')||']');    

    EXECUTE IMMEDIATE 'TRUNCATE TABLE EXP_SOPROMISESRCNCP';    
    
    --TC NETTING으로 차감된 DEMAND 수량은 ASSIGNEDQTY 기존 칼럼에 구성 (FP 후보충 반영할 때는 QTYPROMISED + ASSIGNEDQTY )
    INSERT INTO EXP_SOPROMISESRCNCP
    (ENTERPRISE, SOPROMISEID, PLANID, SALESORDERID, 
     SOLINENUM, ITEM, QTYPROMISED, PROMISEDDELDATE, SITEID, SHIPTOID, 
     SALESID, SALESLEVEL, DEMANDTYPE, WEEK, CUSTOMERRANK, PRODUCTRANK, DEMANDPRIORITY, TIEBREAK, GBM, GLOBALPRIORITY, LOCALPRIORITY, AP2ID, GC, MEASURERANK, PREFERENCERANK, INITDTTM, INITBY, ASSIGNEDQTY)
    SELECT 'SEC' ENTERPRISE,  SOPROMISEID,  PLANID, DEMANDTYPE||'::'||MEASURERANK||'::'||BCKT_IDX||'::'||GCID||'::'||AP2ID||'::'||SALESID||'::'||ITEM||'::'||SITEID||'::'||SOPROMISEID SALESORDERID,
            RANK() OVER(PARTITION BY DEMANDTYPE, MEASURERANK, BCKT_IDX, GCID, AP2ID, SALESID, ITEM, SITEID, SOPROMISEID ORDER BY DEMANDPRIORITY ASC, ROWID) SOLINENUM, 
            ITEM,  QTYPROMISED,  PROMISEDDELDATE, SITEID,  SHIPTOID, 
            SALESID,  SALESLEVEL ,  DEMANTYPERANK DEMANDTYPE,   
            WEEK,   CUSTOMERRANK,  PRODUCTRANK, DEMANDPRIORITY, TIEBREAK, GBM,  GLOBALPRIORITY,  LOCALPRIORITY,
            AP2ID,  GCID,  MEASURERANK, PREFERENCERANK , SYSDATE, 'ENGINE_FINAL', TRNS_QTY
    FROM (
        SELECT 'SEC' ENTERPRISE, 
               CASE WHEN DMD_TYP='EXP_DMD' THEN DECODE(SUBSTR(ORGN_DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM') ELSE DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM') END  SOPROMISEID,
--               CASE WHEN DMD_TYP='EXP_DMD' THEN 2 ELSE 1 END SOLINENUM,
               (SELECT PLAN_ID FROM ODS_VD_DNE.TDN_PLAN) PLANID, 
               SUBSTR(ITEM_ID, 0, INSTR(ITEM_ID, '::', 1, 1)-1) ITEM, PRMS_QTY QTYPROMISED, END_DATE-1 PROMISEDDELDATE, SITE_ID SITEID, SITE_ID SHIPTOID, 
               SALES_ID SALESID, DECODE(SALES_LEVEL,3,'AP2',4, 'AP1', 5,'Account') SALESLEVEL , DMD_TYP_RNK DEMANTYPERANK,  DECODE(DMD_TYP, 'EXP_DMD', ORGN_DMD_TYP,  DMD_TYP) DEMANDTYPE, 
               WEEK_NUM WEEK,  CUST_RNK CUSTOMERRANK, PROD_RNK PRODUCTRANK, FINAL_PRTY DEMANDPRIORITY, WEEK_NUM||DMD_TYP_RNK TIEBREAK, FN_GETGBM GBM, GLBL_PRTY GLOBALPRIORITY, LOCAL_PRTY LOCALPRIORITY,
               AP2_NM AP2ID, GC_NM GCID, MEASURE_TYP_RNK MEASURERANK, PREFR_RNK PREFERENCERANK,  BCKT_IDX, TRNS_QTY
        FROM   ODS_VD_DNE.TDN_EXP_SALES_DMD A
        );
        
        COMMIT;
        
    DBMS_OUTPUT.PUT_LINE('EXP_AP1_DELIVERYPLAN START['||TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')||']');           
        
    DELETE FROM EXP_AP1_DELIVERYPLAN
    WHERE  PLANID = V_PLANID;
        
    --INITIAL PREALLOC SHORT 
    INSERT INTO EXP_AP1_DELIVERYPLAN
    (PLANID, SALESORDERID, SOLINENUM, GBM, SITEID, ITEM, QTYOPEN, QTYPLANNED, PRIORITY,
     PROMISEDSHIPPINGDATE, PLANNEDSHIPMENTDATE, INITDTTM, INITBY)               
    SELECT (SELECT PLAN_ID FROM ODS_VD_DNE.TDN_PLAN) PLANID,  --V_PLANID
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_1@PRE') AS ITEMREQUST,
            RANK() OVER (PARTITION BY (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_1@PRE') ORDER BY FINAL_PRTY, ROWID) SOLINENUM, FN_GETGBM GBM,
            SITE_ID SITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) ITEM, 
            AP2_SHRT_QTY QTYOPEN, 0 QTYPLANNED, 
            FINAL_PRTY PRIORITY, 
            END_DATE-1 PROMISEDSHIPPINGDATE,END_DATE-1 PLANNEDSHIPMENTDATE,
            SYSDATE INITDTTM,'' INITBY
    FROM    ODS_VD_DNE.TDN_EXP_SALES_DMD
    WHERE   AP2_SHRT_REASON IS NOT NULL;                  

    --FINAL PREALLOC SHORT 
    INSERT INTO EXP_AP1_DELIVERYPLAN
    (PLANID, SALESORDERID, SOLINENUM, GBM, SITEID, ITEM, QTYOPEN, QTYPLANNED, PRIORITY,
     PROMISEDSHIPPINGDATE, PLANNEDSHIPMENTDATE, INITDTTM, INITBY)               
    SELECT (SELECT PLAN_ID FROM ODS_VD_DNE.TDN_PLAN) PLANID, 
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_2@PRE') AS ITEMREQUST,
           RANK() OVER (PARTITION BY (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_2@PRE') ORDER BY FINAL_PRTY, ROWID) SOLINENUM,
            FN_GETGBM GBM,
            SITE_ID SITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) ITEM, 
            GC_SHRT_QTY QTYOPEN, 0 QTYPLANNED, 
            FINAL_PRTY PRIORITY, 
            END_DATE-1 PROMISEDSHIPPINGDATE,END_DATE-1 PLANNEDSHIPMENTDATE,
            SYSDATE INITDTTM,'' INITBY
    FROM    ODS_VD_DNE.TDN_EXP_SALES_DMD
    WHERE   GC_SHRT_REASON IS NOT NULL ; 
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('EXP_AP1_SHORTREASON START['||TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')||']');    
    
    DELETE FROM EXP_AP1_SHORTREASON
    WHERE  PLANID = V_PLANID;        
    
    --INITIAL (AP2 PRE ALLOC 수량 INSERT) EXP_AP1_SHORTREASON                
    INSERT INTO EXP_AP1_SHORTREASON
    (PLANID, ITEMREQUEST, PROBLEMID, GBM, SALESORDERID, DUEDATE, REQSITEID, REQITEM, SHORTQTY, PATHID, 
     ORGPROBLEMTYPE, PROBLEMTYPE, PROBLEMDTTM, SITEID, ITEM,  NEEDEDQTY, OPERATION, BOMNAME, BODNAME, 
     INITDTTM, INITBY)
    SELECT (SELECT PLAN_ID FROM ODS_VD_DNE.TDN_PLAN) PLANID, --V_PLANID
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_1@PRE') AS ITEMREQUST,
           '1' PROBLEMID, FN_GETGBM GBM,
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_1@PRE') AS SALESORDERID,
            END_DATE-1 DUEDATE,
            SITE_ID REQSITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) REQITEM,
            AP2_SHRT_QTY SHORTQTY,
            '1' PATHID,
            AP2_SHRT_REASON ORGPROBLEMTYPE, AP2_SHRT_REASON PROBLEMTYPE,
            END_DATE-1 PROBLEMDTTM, 
            SITE_ID SITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) ITEM, 
            AP2_SHRT_QTY NEEDEDQTY,'' OPERATION,'' BOMNAME,'' BODNAME, SYSDATE INITDTTM,'' INITBY
    FROM    ODS_VD_DNE.TDN_EXP_SALES_DMD
    WHERE   AP2_SHRT_REASON IS NOT NULL  ;      
            
    --FINAL(GC PREALLOC)
    INSERT INTO EXP_AP1_SHORTREASON
    (PLANID, ITEMREQUEST, PROBLEMID, GBM, SALESORDERID, DUEDATE, REQSITEID, REQITEM, SHORTQTY, PATHID, 
     ORGPROBLEMTYPE, PROBLEMTYPE, PROBLEMDTTM, SITEID, ITEM, RESOURCENAME, NEEDEDQTY, OPERATION, BOMNAME, BODNAME, 
     INITDTTM, INITBY)
    SELECT (SELECT PLAN_ID FROM ODS_VD_DNE.TDN_PLAN) PLANID, --V_PLANID
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_2@PRE') AS ITEMREQUST,
           '1' PROBLEMID, FN_GETGBM GBM,
           (DMD_TYP||'::'||MEASURE_TYP_RNK||'::'||BCKT_IDX||'::'
                   ||GC_NM||'::'||AP2_NM||'::'||SALES_ID||'::'
                   ||SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1)||'::'||SITE_ID||'::'||DECODE(SUBSTR(DMD_TYP, -3,3),'ORD', ORDER_TYP||'_DM', 'FCST_DM')||'_2@PRE') AS SALESORDERID,
            END_DATE-1 DUEDATE,
            SITE_ID REQSITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) REQITEM, 
            GC_SHRT_QTY SHORTQTY,
            '1' PATHID, GC_SHRT_REASON ORGPROBLEMTYPE, GC_SHRT_REASON PROBLEMTYPE,
            END_DATE-1 PROBLEMDTTM, 
            SITE_ID SITEID, 
            SUBSTR(ITEM_ID,0,INSTR(ITEM_ID,'::')-1) ITEM, 
            '' RESOURCENAME,
            GC_SHRT_QTY NEEDEDQTY,'' OPERATION,'' BOMNAME,'' BODNAME, SYSDATE INITDTTM,'' INITBY
    FROM    ODS_VD_DNE.TDN_EXP_SALES_DMD
    WHERE   GC_SHRT_REASON IS NOT NULL  ;
    
    COMMIT;            

    -- 성능적인 이유로 사용하지 않는 GC Field를 전용해서 SECTION값을 채운다.
    UPDATE EXP_SOPROMISESRCNCP A
    SET GC = (Select SECTION from MST_ITEM Where ITEM = A.ITEM)
    WHERE PLANID = V_PLANID;    
    
    COMMIT;           
     
    DBMS_OUTPUT.PUT_LINE('END ['||TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')||']');        

EXCEPTION
 WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLCODE ||':: '||SUBSTR(SQLERRM, 1, 2000));
END;
